[package]
name = "paa5100je-pmw3901"
version = "0.1.0"
edition = "2021"
authors = ["Pete Kubiak <peter.kubiak@dyson.com>"]

[features]
sync = ["maybe-async/is_sync"]
default = ["defmt"]
defmt = ["dep:defmt"]

[dependencies]
maybe-async = { version = "0.2.10" }
embedded-hal = { version = "*" }
embedded-hal-async = { version = "*" }
defmt = { version =  "1.0.1", optional = true }
bytemuck = { version = "1.21.0", features = ["derive"] }
